### PR TITLE
Reworking cellline Case / Sample / Aliquot relationships

### PR DESCRIPTION
**Pull request by adamstruck**
- Samples / Aliquots belong to each Program / Project.  
- Added edges from Project to Sample / Aliquot and from Phenotype to Case / Sample. 

Still working on the GDSC transform...

### CODE REVIEW

**Comment by adamstruck** [comment]
closes: #314, #315

**Comment by kellrott** [comment]
Add `xlrd` to the python requirements

**Comment by kellrott** [comment]
Lots of null values in the GDSC DrugResponse output:

```
{"_id": "DrugResponse:gdsc:ACH-002137:Erlotinib", "gid": "DrugResponse:gdsc:ACH-002137:Erlotinib", "label": "DrugResponse", "data": {"source": "gdsc", "submitter_id": "ACH-002137", "submitter_compound_id": "Erlotinib", "ic50": NaN, "act_area": NaN}}
{"_id": "DrugResponse:gdsc:ACH-000474:Erlotinib", "gid": "DrugResponse:gdsc:ACH-000474:Erlotinib", "label": "DrugResponse", "data": {"source": "gdsc", "submitter_id": "ACH-000474", "submitter_compound_id": "Erlotinib", "ic50": NaN, "act_area": NaN}}
{"_id": "DrugResponse:gdsc:ACH-002089:Erlotinib", "gid": "DrugResponse:gdsc:ACH-002089:Erlotinib", "label": "DrugResponse", "data": {"source": "gdsc", "submitter_id": "ACH-002089", "submitter_compound_id": "Erlotinib", "ic50": NaN, "act_area": NaN}}
```

**Comment by adamstruck** [comment]
@kellrott those null value are in the source data I am pulling from DepMap.

**Comment by adamstruck** [comment]
@bwalsh any idea why the phenotype unit test is failing?

**Comment by bwalsh** [comment]
bio ontology seems to be partially down.
image

**Comment by adamstruck** [comment]
Current report of missing vertices from `check-graph`:

```
{"Project":1,"Transcript":129,"Gene":1124,"Aliquot":502,"GO":26,"Protein":15195,"PFAMFamily":3,"PFAMClan":4}
```

**Comment by adamstruck** [comment]
Most recent commit should fix the missing aliquots for GDSC and adds an 'auc' property to the DrugResponse vertex to address #325

**Comment by adamstruck** [comment]
@kellrott @bwalsh this PR is ready for review.

**Pull request merged**
