### PR TITLE
Postgres

### PR DESCRIPTION
**Pull request by bwalsh**
This PR contains:
* docker-compose.yml file for development
* loader script to load vertexes and edges
* postgres DDL to create tables
Addresses #193

### CODE REVIEW

**Comment by bwalsh** [comment]
@adamstruck  @kellrott  @buchanae  Would be useful to  have a whiteboard talk re.  quick lessons learned? https://github.com/bmeg/bmeg-etl/tree/postgres/postgres

**Comment by adamstruck** [comment]
@bwalsh yes I think that would be a good idea.

**Comment by bwalsh** [comment]
@adamstruck @kellrott Just a wip:  findings:
* postgres/README.md
* postgres/agensgraph/README.md

**Comment by bwalsh** [comment]
added #225

**Pull request closed without merging**
